### ISSUE TITLE
what permissions are needed for TOKEN_FOR_CODESPACES 

### ISSUE THREAD

**Issue by xmatthias** [dlemstra/github-actions-debugger#1]
Hi @dlemstra,

Thanks for this - i can see great benefits in this action!

From the demo repository, I've taken the following configuration.

```
    - name: Debug in Codespace
      # if: failure()
      uses: dlemstra/github-actions-debugger@main
      with:
        token: ${{ secrets.TOKEN_FOR_CODESPACES }}
        codespace: ${{ inputs.codespace }}
```

Unfortunately, i couldn't really find what `TOKEN_FOR_CODESPACES` is (it's defined as secret - but what type of token is this?
assuming it's a github Personal access token - what permissions will it need? (ideally, i'd want to use fine-grained PAT, but it's difficult to understand the necessary permissions without reviewing the full action).

you may also want to work on the error output if that token is missing, it's kindof misleading to say "no codespace provided" - while in reality, it's missing the token.

![grafik](https://github.com/dlemstra/github-actions-debugger/assets/5024695/98c931c6-67c5-4aa8-bdf5-176ede7b21b9)
